ignoredBuiltDependencies:
  - prisma-zod-generator

onlyBuiltDependencies:
  - '@prisma/engines'
  - better-sqlite3
  - core-js
  - esbuild
  - prisma
  - sharp
  - unrs-resolver

overrides:
  hono@<4.11.7: '>=4.11.7'
  lodash@>=4.0.0 <=4.17.22: '>=4.17.23'
